/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Dds_Formularios_Confeitaria;

import Dds_Objeto.Dds_Bolo;
import com.google.gson.Gson;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dionnes
 */
public class Dds_Cadastro_Bolos extends javax.swing.JFrame {

    /**
     * Creates new form Dds_Cadastro_Bolos
     */
    public void Dds_limparCampos() {
        Dds_NomeBolo.setText("");
        Dds_tipoBolo.setSelectedItem("");
        Dds_Cobertura.setSelectedItem("");
        Dds_Recheio.setSelectedItem("");
        Dds_Tamanho.setSelectedItem("");
        Dds_Valor.setText("");
        Dds_Data.setText("");
    }

    public Dds_Cadastro_Bolos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dds_Cadastro = new javax.swing.JPanel();
        Dds_Titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Dds_NomeBolo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Dds_tipoBolo = new javax.swing.JComboBox<>();
        Dds_Cobertura = new javax.swing.JComboBox<>();
        Dds_Recheio = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        Dds_Valor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Dds_Tamanho = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        Dds_Data = new javax.swing.JTextField();
        Dds_BotaoSalvar = new javax.swing.JButton();
        Dds_Button_Menu = new javax.swing.JButton();
        Dds_ButtonEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Dds_Titulo.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        Dds_Titulo.setText("Cadastro de bolos");

        jLabel2.setText("Nome do bolo:");

        jLabel3.setText("Tipo de bolo:");

        jLabel1.setText("Cobertura:");

        jLabel4.setText("Recheio:");

        Dds_tipoBolo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bolo para Festa", "Bolo simples", " " }));
        Dds_tipoBolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dds_tipoBoloActionPerformed(evt);
            }
        });

        Dds_Cobertura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cobertura simples", "Cobertura com tema", " " }));

        Dds_Recheio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chocolate", "Ninho", "Beijinho", "Caramelo", "Chocolate com Ninho", "Ninho com Beijinho", "Chocolate com Beijinho" }));

        jLabel5.setText("Valor Do Bolo:");

        jLabel6.setText("Tamanho Do Bolo:");

        Dds_Tamanho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "P", "M", "G" }));

        jLabel7.setText("Data de validade:");

        Dds_BotaoSalvar.setText("Salvar");
        Dds_BotaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dds_BotaoSalvarActionPerformed(evt);
            }
        });

        Dds_Button_Menu.setText("Menu");
        Dds_Button_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dds_Button_MenuActionPerformed(evt);
            }
        });

        Dds_ButtonEditar.setText("Editar");
        Dds_ButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dds_ButtonEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Dds_CadastroLayout = new javax.swing.GroupLayout(Dds_Cadastro);
        Dds_Cadastro.setLayout(Dds_CadastroLayout);
        Dds_CadastroLayout.setHorizontalGroup(
            Dds_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dds_CadastroLayout.createSequentialGroup()
                .addGroup(Dds_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dds_CadastroLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(Dds_Titulo))
                    .addGroup(Dds_CadastroLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(Dds_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Dds_CadastroLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dds_Tamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Dds_CadastroLayout.createSequentialGroup()
                                .addGroup(Dds_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Dds_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Dds_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Dds_NomeBolo)
                                    .addComponent(Dds_tipoBolo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Dds_Cobertura, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Dds_Recheio, 0, 217, Short.MAX_VALUE)
                                    .addComponent(Dds_Valor)
                                    .addGroup(Dds_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Dds_ButtonEditar)
                                        .addComponent(Dds_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(Dds_CadastroLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(Dds_BotaoSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Dds_Button_Menu)))))
                .addGap(41, 41, 41))
        );
        Dds_CadastroLayout.setVerticalGroup(
            Dds_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dds_CadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Dds_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Dds_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Dds_NomeBolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Dds_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Dds_tipoBolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Dds_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Dds_Cobertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Dds_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Dds_Recheio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Dds_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Dds_Tamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Dds_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Dds_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(Dds_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Dds_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(Dds_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dds_BotaoSalvar)
                    .addComponent(Dds_Button_Menu)
                    .addComponent(Dds_ButtonEditar))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dds_Cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dds_Cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Dds_tipoBoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dds_tipoBoloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Dds_tipoBoloActionPerformed

    private void Dds_BotaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dds_BotaoSalvarActionPerformed
        Gson gson = new Gson();
        try {
            Socket Dds_con;
            Dds_con = new Socket("127.0.0.1", 1234);
            Dds_Bolo Dds_B = new Dds_Bolo();
            Dds_B.setDds_NomeBolo(Dds_NomeBolo.getText());
            Dds_B.setDds_tipoBolo(Dds_tipoBolo.getSelectedItem().toString());
            Dds_B.setDds_Cobertura(Dds_Cobertura.getSelectedItem().toString());
            Dds_B.setDds_Tamanho(Dds_Tamanho.getSelectedItem().toString());
            Dds_B.setDds_Valor(Dds_Valor.getText());
            Dds_B.setDds_Data(Dds_Data.getText());

            String Dds_ObjetoJson = gson.toJson(Dds_B);
            PrintStream Dds_Saida = new PrintStream(Dds_con.getOutputStream());
            Dds_Saida.println(Dds_ObjetoJson);
            Dds_limparCampos();
            JOptionPane.showMessageDialog(this, "Salvo com sucesso!");

            Dds_con.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_Dds_BotaoSalvarActionPerformed

    private void Dds_Button_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dds_Button_MenuActionPerformed
        new Dds_Menu_Principal().setVisible(true);
        dispose();
    }//GEN-LAST:event_Dds_Button_MenuActionPerformed

    private void Dds_ButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dds_ButtonEditarActionPerformed
        Gson gson = new Gson();

        try {
            Dds_Bolo Dds_B = new Dds_Bolo();
            Socket Dds_con = new Socket("127.0.0.1", 1234);
            PrintStream Dds_Saida = new PrintStream(Dds_con.getOutputStream());
            Dds_Saida.println("Buscar");
            BufferedReader Dds_Entrada = new BufferedReader(new InputStreamReader(Dds_con.getInputStream()));
            String Dds_ObjetoJson = Dds_Entrada.readLine();
            
            Dds_B = gson.fromJson(Dds_ObjetoJson, Dds_Bolo.class);
            
            Dds_NomeBolo.setText(Dds_B.getDds_NomeBolo());
            Dds_tipoBolo.setSelectedItem(Dds_B.getDds_tipoBolo().toString());
            Dds_Cobertura.setSelectedItem(Dds_B.getDds_Cobertura().toString());
            Dds_Recheio.setSelectedItem(Dds_B.getDds_Recheio().toString());
            Dds_Tamanho.setSelectedItem(Dds_B.getDds_Tamanho().toString());
            Dds_Valor.setText(Dds_B.getDds_Valor());
            Dds_Data.setText(Dds_B.getDds_Data());
            
            Dds_con.close();
            
        } catch (IOException ex) {
            
        }

    }//GEN-LAST:event_Dds_ButtonEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dds_Cadastro_Bolos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dds_Cadastro_Bolos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dds_Cadastro_Bolos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dds_Cadastro_Bolos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dds_Cadastro_Bolos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dds_BotaoSalvar;
    private javax.swing.JButton Dds_ButtonEditar;
    private javax.swing.JButton Dds_Button_Menu;
    private javax.swing.JPanel Dds_Cadastro;
    private javax.swing.JComboBox<String> Dds_Cobertura;
    private javax.swing.JTextField Dds_Data;
    private javax.swing.JTextField Dds_NomeBolo;
    private javax.swing.JComboBox<String> Dds_Recheio;
    private javax.swing.JComboBox<String> Dds_Tamanho;
    private javax.swing.JLabel Dds_Titulo;
    private javax.swing.JTextField Dds_Valor;
    private javax.swing.JComboBox<String> Dds_tipoBolo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
