/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Dds_Formularios_Confeitaria;

import Dds_Objeto.Dds_Bolo;
import com.google.gson.Gson;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.net.Socket;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dionnes
 */
public class Dds_Formulario_Relatorio extends javax.swing.JFrame implements Runnable{
     private Socket Dds_conexao;
      Thread Dds_t;
   
     private void Dds_preencherTab(String Dds_Si){
         Gson Dds_gson = new Gson();
         
         try {
             Dds_Bolo Dds_B;
             
             Socket Dds_con = new  Socket("127.0.0.1",2222);
             PrintStream Dds_saida  = new PrintStream(Dds_con.getOutputStream());
             Dds_saida.println("Buscar");
             
              BufferedReader Dds_entrada = new BufferedReader(
                    new InputStreamReader(Dds_con.getInputStream()));
            
            DefaultTableModel Dds_TBolos = (DefaultTableModel)Dds_TabelaBolos.getModel();
            
            String Dds_linha;
            Dds_TBolos.setNumRows(0);            
            while(true)
            {   
                Dds_linha = Dds_entrada.readLine();
                              
                if(Dds_linha != null && Dds_linha.trim().length()!=0)
                {   
                    Dds_B = Dds_gson.fromJson(Dds_linha, Dds_Bolo.class);
                    Dds_TBolos.addRow(new Object[]{Dds_B.getDds_NomeBolo(),Dds_B.getDds_tipoBolo(),Dds_B.getDds_Cobertura(),
                    Dds_B.getDds_Recheio(),Dds_B.getDds_Tamanho(), Dds_B.getDds_Valor(), Dds_B.getDds_Data()});
                }
            }  
         } catch (Exception e) {
             e.printStackTrace();
         }
     }
     
    public void run() {        
        Dds_preencherTab("Inicio");
        
    }
    public Dds_Formulario_Relatorio() {
        initComponents();
        
         try
        {            
            Socket Dds_con = new Socket("127.0.0.1", 2222);
            this.Dds_conexao = Dds_con;
            Dds_t = new Thread(this);            
            Dds_t.start();            
        }
        catch(IOException e)
        {
            e.printStackTrace();
        }         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Dds_TabelaBolos = new javax.swing.JTable();
        Dds_Atualizar = new javax.swing.JButton();
        Dds_ButtonMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Dds_TabelaBolos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome Do Bolo", "Tipo De Bolo", "Cobertura", "Recheio", "Tamanho", "Valor Do Bolo", "Data Validade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Dds_TabelaBolos);

        Dds_Atualizar.setText("Atualizar");

        Dds_ButtonMenu.setText("Menu");
        Dds_ButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dds_ButtonMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(Dds_Atualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Dds_ButtonMenu)
                .addGap(90, 90, 90))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dds_Atualizar)
                    .addComponent(Dds_ButtonMenu))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Dds_ButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dds_ButtonMenuActionPerformed
       new Dds_Menu_Principal().setVisible(true);
       dispose();
    }//GEN-LAST:event_Dds_ButtonMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dds_Formulario_Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dds_Formulario_Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dds_Formulario_Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dds_Formulario_Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dds_Formulario_Relatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dds_Atualizar;
    private javax.swing.JButton Dds_ButtonMenu;
    private javax.swing.JTable Dds_TabelaBolos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
